#!/bin/bash
# 📊 Monitor GPU Script
# Automatically generated by Antigravity

if command -v nvidia-smi &> /dev/null; then
    watch -n 1 nvidia-smi
else
    echo "❌ nvidia-smi not found. This script is intended for NVIDIA GPUs."
fi
