#!/bin/bash
# 🚀 Start Training Script for RTX 5090
# Automatically generated by Antigravity

# Activate virtual environment
if [ -d "venv" ]; then
    source venv/bin/activate
elif [ -d "venv_stable" ]; then
    source venv_stable/bin/activate
else
    echo "⚠️  Warning: venv not found. Running with system python."
fi

# Run training
python train_cloud_5090.py \
    --full_pipeline \
    --run_tests \
    --num_epochs 4 \
    --data_path data/parquets/train0901-00000-of-00003.parquet \
    --output_dir runs/distill_5090
